"""added selected_size and seelceted_color in cart model

Revision ID: 07106548e312
Revises: 8338408aea6e
Create Date: 2026-06-03 10:31:15.960112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07106548e312'
down_revision: Union[str, Sequence[str], None] = '8338408aea6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('selected_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cart', sa.Column('selected_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'selected_color')
    op.drop_column('cart', 'selected_size')
    # ### end Alembic commands ###
