"""added email and number verified boolean fiedls in user

Revision ID: 1604cf88534d
Revises: 1c0fd2805fd6
Create Date: 2026-06-16 11:17:00.600004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "1604cf88534d"
down_revision: Union[str, Sequence[str], None] = "1c0fd2805fd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )

    op.add_column(
        "user",
        sa.Column(
            "phone_verified",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone_verified")
    op.drop_column("user", "email_verified")
    # ### end Alembic commands ###
